---
driver:
  require_chef_omnibus: <%= ENV.fetch("CHEF_VERSION", "latest") %>
  ssh_key: <%= File.expand_path("./test/support/keys/vagrant") %>
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[newrelic-sysmond]
    attributes:
      new_relic:
        license_key: <%= ENV.fetch("NEWRELIC_SYSMOND_LICENSE_KEY", "invalid-license-key") %>
